//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GraphicTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int DISPLAYMODE {
            get {
                return ((int)(this["DISPLAYMODE"]));
            }
            set {
                this["DISPLAYMODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RECENTFILES {
            get {
                return ((string)(this["RECENTFILES"]));
            }
            set {
                this["RECENTFILES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SHOWDISPLAYINFO {
            get {
                return ((bool)(this["SHOWDISPLAYINFO"]));
            }
            set {
                this["SHOWDISPLAYINFO"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10;10;800;800")]
        public string DESKTOPBOUNDS {
            get {
                return ((string)(this["DESKTOPBOUNDS"]));
            }
            set {
                this["DESKTOPBOUNDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SHOWSAVEIMAGETOBACKGROUNDWARNING {
            get {
                return ((bool)(this["SHOWSAVEIMAGETOBACKGROUNDWARNING"]));
            }
            set {
                this["SHOWSAVEIMAGETOBACKGROUNDWARNING"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Type=""Rectangle"" TextAlign=""left"" VerticalAlign=""top"" PaddingLeft=""5"" PaddingBottom=""0"" PaddingRight=""0"" PaddingTop=""5"" X=""5"" Y=""5"" Width=""50"" Height=""50"" LineColor=""#ff0000"" LineWidth=""2"" Transparency=""0"" ShapeTimeSpan=""10000"" Right=""0"" Bottom=""0"" Left=""5"" Top=""5"" BackgroundColor=""transparent"" Color=""Black"" FontWeight=""normal"" FontStyle=""normal"" FontFamily=""Segoe UI"" FontSize=""10pt"" Underline=""false"" ")]
        public string RECTANGLE {
            get {
                return ((string)(this["RECTANGLE"]));
            }
            set {
                this["RECTANGLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Type=""Oval"" TextAlign=""left"" VerticalAlign=""top"" PaddingLeft=""5"" PaddingBottom=""0"" PaddingRight=""0"" PaddingTop=""5"" X=""5"" Y=""5"" Width=""40"" Height=""40"" ShapeTimeSpan=""10000"" Right=""5"" Bottom=""0"" LineColor=""#ff0000"" LineWidth=""2"" Transparency=""0"" Rotate=""0"" Anchors="""" FontWeight=""normal"" FontStyle=""normal"" FontFamily=""Segoe UI"" FontSize=""10pt"" Underline=""false""  Color=""Black"" Left=""0"" Top=""5""")]
        public string OVAL {
            get {
                return ((string)(this["OVAL"]));
            }
            set {
                this["OVAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"Type=""Polyline"" Coordinates=""10,10,50,50"" ArrowHeadColor=""#ff0000"" ArrowTailColor=""#ff0000"" BackgroundColor=""#ff0000"" BackgroundColorAlt=""#ff0000"" LineColor=""#ff0000"" LineWidth=""2"" VerticalAlign=""4"" TextAlign=""1"" PaddingLeft=""5"" PaddingBottom=""0"" PaddingRight=""0"" PaddingTop=""5"" Conditions=""""")]
        public string POLYLINE {
            get {
                return ((string)(this["POLYLINE"]));
            }
            set {
                this["POLYLINE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string RECENTXPATHS {
            get {
                return ((string)(this["RECENTXPATHS"]));
            }
            set {
                this["RECENTXPATHS"] = value;
            }
        }
    }
}
